[workspace]
members = ["sys"]

[workspace.package]
authors = ["wiiznokes <wiiznokes2@gmail.com>"]
edition = "2024"
license = "MIT"
homepage = "https://github.com/wiiznokes/rnnoise-rs/"
repository = "https://github.com/wiiznokes/rnnoise-rs.git"
keywords = ["audio"]

[package]
name = "rnnoise-rs"
version = "0.1.0"
license.workspace = true
edition.workspace = true
keywords.workspace = true

[workspace.dependencies]

[dependencies]
rnnoise2-sys = { path = "sys" }
