[workspace]
members = ["sys"]

[workspace.package]
authors = ["wiiznokes <wiiznokes2@gmail.com>"]
edition = "2024"
license = "MIT"
homepage = "https://github.com/wiiznokes/rnnoise-rs/"
repository = "https://github.com/wiiznokes/rnnoise-rs.git"
keywords = ["audio"]

[package]
name = "rnnoise2"
version = "0.1.1"
description = """
Abstraction arround the rnnoise C bindings
"""
readme = "README.md"
license.workspace = true
edition.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true

[workspace.dependencies]

[features]
runtime-model = ["rnnoise2-sys/runtime-model"]

[dependencies]
rnnoise2-sys = { path = "sys", version = "0.1" }

[package.metadata.docs.rs]
features = ["runtime-model"]
